{
  username: "xiangyi";
  userfullname: "MENG Xiangyi";
  useremail: "xymeng16@gmail.com";
  # networking = import ./networking.nix {inherit lib;};
  # generated by `mkpasswd -m sha-512`
  initialHashedPassword = "$6$9tt0xsK0rxV657K7$RfR6vN0/.318cNs7EF.3mhKmUMW7saLSjVran3maqHkYr8q4P7HsqY/zfUDIsaFcuhatL1SwhiODzFAx9WQgw1";
  sshAuthorizedKeys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4ftbnxeQ2SEPZgL/A5u7zfDbP6WuUdkrNw94kK37BPTLJfb37XLJTUx07aSBgI9uWN3n/W7VBh55W77eOcqzjaGUgbx2VxRoLAJeZxCH3j+uAYyQZqSJeVOT+GDB1AsCux42y5lKwA87bz/Z6f+IhNk3uGBf5VE+gT8Jf0i5eBt3UOb5Dbqs85KBAuzyr8/sSAXxcMg6MPpOkrMz9N2PBSnd7lW90rsLSvW2+A38aUHemnBadDlUMhreq0NPNgxjhzkhgLxpuyQzv325oFXP0ahHydii4CblnQm0rewzr7NLFk7b7m1O2YWFKziBkC5MvraJZvwZ0jUfVbaMR0ptpOPfcBck4Eu5MFU+JIpBDAMPBgWLV+S5awi9IjnlHldiu8bjui+h3QD6Paw7TT40b/Dk0v0XkJ2ZqfnperW92swgKs9TFZaW9mHdrQ/uAB7jwUjBtjCJzep5fnUrO2hqRNiHWOzEkar4V2XeoPe10nvxC95W/TbZ4FIO9R2epaN8= xiangyi@Xiangyis-Mac-mini.local"
  ];
}
